# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c55287cc2d4860ad72c9f401841f58a6732b02f66c43b875f6ae5c562e05ef9631178ceec1b58c9553f250c429af50071fe641e230529760f9d572f1b1780f8a

test:
  secret_key_base: 9c1453b8ecb47ae403550ccb37ad884fa949ce3ded642180763d6cffc65c36ab13695cf0aa08f521c28d792ee01b88e39ca3278b6a50ee1545d0b81b1e66d1cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
